// Code generated by MockGen. DO NOT EDIT.
// Source: api_invoker.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	model "example.com/covid-go/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockApiInvokerInterface is a mock of ApiInvokerInterface interface
type MockApiInvokerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockApiInvokerInterfaceMockRecorder
}

// MockApiInvokerInterfaceMockRecorder is the mock recorder for MockApiInvokerInterface
type MockApiInvokerInterfaceMockRecorder struct {
	mock *MockApiInvokerInterface
}

// NewMockApiInvokerInterface creates a new mock instance
func NewMockApiInvokerInterface(ctrl *gomock.Controller) *MockApiInvokerInterface {
	mock := &MockApiInvokerInterface{ctrl: ctrl}
	mock.recorder = &MockApiInvokerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockApiInvokerInterface) EXPECT() *MockApiInvokerInterfaceMockRecorder {
	return m.recorder
}

// GetCovid19Data mocks base method
func (m *MockApiInvokerInterface) GetCovid19Data() (model.CovidData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCovid19Data")
	ret0, _ := ret[0].(model.CovidData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCovid19Data indicates an expected call of GetCovid19Data
func (mr *MockApiInvokerInterfaceMockRecorder) GetCovid19Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCovid19Data", reflect.TypeOf((*MockApiInvokerInterface)(nil).GetCovid19Data))
}
